spring.application.name=delivery
# Enable Liquibase
spring.liquibase.enabled=true
server.port=8083
# Path to master changelog
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:deliverydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=none
# Enable H2 Web Console at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.level.liquibase=DEBUG
logging.level.org.liquibase=DEBUG
